table DimCustomer
	lineageTag: 204880c4-5696-45e8-bc40-b543a463a0b0

	column CustomerID
		dataType: int64
		formatString: 0
		lineageTag: 80124d96-c8ea-4fff-bc27-301b391d10dd
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column Customer
		dataType: string
		lineageTag: 3873e5ad-d610-4925-bf96-6ba0c12ec79d
		summarizeBy: none
		sourceColumn: Customer

		annotation SummarizationSetBy = Automatic

	column CustomerGroup
		dataType: string
		lineageTag: 01dd5d46-bd02-4b7b-90be-74fa0093122a
		summarizeBy: none
		sourceColumn: CustomerGroup

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 8c1b992e-1f95-4f1e-94bc-50b2321b1498
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: b7979150-1b5f-4ad4-bb58-adb7a0a223da
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 9313aab5-232d-4ff6-bad5-0ffaf889820e
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	partition DimCustomer = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\perumalm\Documents\Github copilot\Git_Copilot_POC.xlsx"), null, true),
				    DimCustomer_Sheet = Source{[Item="DimCustomer",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(DimCustomer_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CustomerID", Int64.Type}, {"Customer", type text}, {"CustomerGroup", type text}, {"State", type text}, {"Region", type text}, {"Country", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

